version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
    - "27017:27017"
    volumes:
    - dbdata:/data/db
    networks:
    - webservice_network

  webservice:
    build:
      context: .
      dockerfile: Dockerfile-server
    depends_on:
    - db
    networks:
    - webservice_network

volumes:
  dbdata:

networks:
  webservice_network: {}